# GitHub Sponsors - Hidden until ready
# github: [semalytics]
# open_collective: paired

# Custom funding links - Hidden until ready
# custom: ['https://semalytics.com/sponsor', 'https://buymeacoffee.com/paired']
