name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what went wrong
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Run paired-doctor and paste output
    validations:
      required: true
